name: CI

on: [push, pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
        - swift:5.3
        - swift:5.4
        - swiftlang/swift:nightly-main
    container: ${{ matrix.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Resolve Swift dependencies
        run: swift package resolve
      - name: Build & Test
        run: swift test --enable-test-discovery --parallel

  release-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
        - swift:5.3
        - swift:5.4
        - swift:5.5
        - swiftlang/swift:nightly-main
    container: ${{ matrix.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Resolve Swift dependencies
        run: swift package resolve
      - name: Build in release mode
        run: swift build --enable-test-discovery -c release
